server.port=8003

spring.application.name=search-service

# ES的日志门槛
logging.level.cn.tedu.knows.search=debug
logging.level.org.elasticsearch.client.RestClient=debug

# 指定连接的ES的地址和端口
spring.elasticsearch.rest.uris=http://localhost:9200

spring.cloud.nacos.discovery.server-addr=localhost:8848

