server.port=8899


spring.resources.static-locations=file:D:/upload


#定义当前微服务的项目名称,当前项目会使用这个名称注册到nacos
spring.application.name=resource-server

#定义正在运行的Nacos的位置,其实就是ip和端口号
spring.cloud.nacos.discovery.server-addr=localhost:8848


server.servlet.context-path=/image

#上传文件需要的路径和服务器端口
knows.resource.path=file:D:/upload
knows.resource.host=http://localhost:9000/image
